platzigram/urls.py
"""platzigram URL Configuration

"""
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('posts.urls', 'posts'), namespace='posts')),
    path('users/', include(('users.urls', 'users'), namespace='users')),



] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

posts/urls.py
"""POST URLS"""
#django 
from django.urls import path 

from posts import views

urlpatterns=[
    path(
        route='',
        view = views.PostFeedView.as_view(), 
        name='feed'),
    path(
        route='posts/new/', 
        view=views.CreatePostView.as_view(), 
        name='create_post'),
    path(
        route='posts/<int:pk>/',
        view=views.PostDetailView.as_view(),
        name='detail'
        )
    
]

users/urls.py
"""Users Urls"""

#django 
from django.urls import path
from users import views


urlpatterns=[
        
    path(
        route='login/', 
        view=views.LoginView.as_view(), 
        name='login'),
    path(
        route='logout/', 
        view=views.logout_view, 
        name='logout'),
    path(
        route='singup/', 
        view=views.SigunView.as_view(), 
        name='signup'),
    path(
        route='me/profile/', 
        view=views.UpdateProfileView.as_view(), 
        name='update'),
        
    path(
        route='<str:username>/',
        view=views.UserDetailView.as_view(),
        name='detail'
        ),
]

posts/models.py
"""Post models."""

from django.db import models
from django.contrib.auth.models import User

class Post(models.Model):

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    profield = models.ForeignKey('users.Profile', on_delete = models.CASCADE)
    title = models.CharField(max_length=255)
    photo = models.ImageField(upload_to='post/photos')
    created = models.DateField(auto_now_add=True)
    modified = models.DateField(auto_now=True)

    def __str__(self):
        """return user an title """
        return '{} by {}'.format(self.title, self.username)
    

users/models.py
from django.contrib.auth.models import User
from django.db import models


# Create your models here.
class Profile(models.Model):
    """profile model.
        proxi model tat etends the base model from user
    """

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    website = models.URLField(max_length=200, blank=True)
    biograpy = models.TextField( blank=True)
    phone_number = models.CharField(max_length=20, blank= True)
    picture =  models.ImageField(upload_to='users/pictures', blank= True, null= True)
    created = models.DateField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)


    """para retornar el string enves del user name """
    def __str__(self):
        return self.user.username
    

posts/forms.py
"""Post From  """

from django import forms

from  posts.models import Post

class PostForm(forms.ModelForm):
    model = Post
    fields = ('user', 'profile', 'title', 'photo')
    

users/forms.py
"""user forms."""
# Django 
from django import forms
#modelo
from django.contrib.auth.models import User
from users.models import Profile

class SigupForm(forms.Form):
    """Sign up form """
    username = forms.CharField(min_length =4, max_length = 50, required = True)
    password = forms.CharField(max_length = 70, widget = forms.PasswordInput())
    password_confirmation = forms.CharField(max_length=70, widget = forms.PasswordInput())
    first_name = forms.CharField(min_length= 2, max_length=70)
    last_name = forms.CharField(min_length=2, max_length=50)
    email = forms.CharField(
        min_length=7,
        max_length=70,
        widget= forms.EmailInput()
    )

    def clean_username(self):
        """username must be unique"""
        username = self.cleaned_data['username']
        username_taken = User.objects.filter(username = username).exists()
        if username_taken:
            raise forms.ValidationError('Username is already in use.')
        return username

    def clean(self):
        """verify password confimation """
        data = super().clean()
        password = data['password']
        password_confirmation = data['password_confirmation']
        if password != password_confirmation:
            raise forms.ValidationError('Password do not match.')
        return data
    def safe(self):
        """ create user and profile """
        data = self.cleaned_data
        data.pop('password_confirmation')
        user = User.objects.create_user(**data)
        profile = Profile(user=user)
        profile.save()




    

posts/views.py
"""Posts views."""


#django 
#from django.shortcuts import render
#from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy
from django.shortcuts import render, redirect
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView DetailView CreateView

# froms 
from posts.forms import PostForm
# models
from posts.models import Post


#utilitis
from datetime import datetime



class PostFeedView(LoginRequiredMixin, ListView):
    """Return all pubshiedl post """
    template_name  = 'posts/reed.html'
    model = Post
    ordering = ('-created',)
    paginate_by=2
    context_object_name = 'posts'


class PostDetailView(LoginRequredMixin, DetailView):
    """Return post Detail ."""
    template_name= 'post/detail.html'
    queryset=Post.objects.all()
    context_object_name='posts'

class CreatePostView(LoginRequiredMixin, CreateView):
    """ Create a new post """
    tempalte_name = 'posts/new.html'
    from_class = PostForm
    success_url = reverse_lazy('posts:feed')
    
    def get_context_data(self, **kwargs):
        """Add user and profle to context """
        context = super().get_context_data(**kwargs)
        context['user']= self.request.user
        context['profile']= self.request.user.profile
        return context

users/views.py
""" users views"""
from django.shortcuts import render
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import views as auth_views
from django.shortcuts import render, redirect
from django.views.generic import DetailView, FormView, UpdateView
from django.urls import reverse, reverse_lazy 
# Exeptions
from django.db.utils import IntegrityError
#models
from django.contrib.auth.models import User
from users.models import Profile
from post.models import Post

# Forms
from users.forms import Profileform, SigupForm


class UserDetailView(LoginRequireMixin, DetailView):
    """User detail  view"""
    template_name = 'users/detail.html'
    slug_filed = 'username'
    slug_url_kwarg = 'username'
    queryset = User.objects.all()
    context_object = 'user'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = self.get_object()
        context['post'] = Post.objects.filter(user=user).order_by('-created')
        return context
    
class SignupView(FromView):
    template_name = 'users/signup.html'
    from_class = SigunForm
    succes_url = reverse_lazy('users:login')

    def form_falid(self, form):
        """ save from data."""
        form.save()
        return super().form_valid(form)



class UpdateProfileView(LoginRequiredMixin, UpdateView):
    template_name = 'users/update_profile.html'
    model = Profile 
    fields = ['website', 'biograpy', 'phone_number', 'picture']

    def get_ogject(self):
        return self.request.user.prfile

    def get_success_url(self):
        """ return to users profile """
        username = self.object.user.username
        return reverse('users:detail', kwargs = {'username': username})
        
class LoginView(auth_views.LoginView):
    """ logiin view"""
    template_name = 'users/login.html'



class LogoutView(LoginRequiredMixin, auth_views.LogoutView):
    """ logout view"""
    tempalte_name = 'users/logged_out.html'

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block head_content %}{% endblock %}


    {% load static %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" crossorigin="anonymous" />
    <link rel="stylesheet" href="{% static 'css/main.css' %}" />

</head>
<body>

    {% include "nav.html" %}

    <div class="container mt-5">
        {% block container %}
        {% endblock%}
    </div>

</body>
</html>

templates/nav.html
{% load static %}
<nav class="navbar navbar-expand-lg fixed-top" id="main-navbar">
    <div class="container">

        <a class="navbar-brand pr-5" style="border-right: 1px solid #efefef;" href="{% url 'posts:feed' %}">
            <img src="{% static "img/instagram.png" %}" height="45" class="d-inline-block align-top"/>
        </a>

        <div class="collapse navbar-collapse">
            <ul class="navbar-nav mr-auto">

                <li class="nav-item">
                    <a href="{% url 'users:detail" request.user.username %}">
                        {% if request.user.profile.picture %}
                            <img src="{{ request.user.profile.picture.url }}" height="35" class="d-inline-block align-top rounded-circle"/>
                        
                        {% else %}
                            <img src="{% static 'img/default-profile.png' %}" height="35" class="d-inline-block align-top rounded-circle"/>
                        {% endif %}
                    </a>
                </li>

                <li class="nav-item nav-icon">
                    <a href="{% url 'posts:create_post' %}">
                        <i class="fas fa-plus"></i>
                    </a>
                </li>

                <li class="nav-item nav-icon">
                    <a href="{% url 'users:logout' %}">
                        <i class="fas fa-sign-out-alt"></i>
                    </a>
                </li>

            </ul>
        </div>
    </div>
</nav>

templates/pagination.html
    <nav>
        <ul class="pagination justify-content-end">
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.previus_page_number }}">
               Previous 
                </a>
            </li> 
            <li class="page-item">
           
                <a class="page-link" href="#">
                    {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
                </a>
            </li> 
            <li class="page-item">

                <a class="page-link" href="?page={{ page_obj.next_page_number }}">
                Next
                </a>
            </li> 
        </ul>
        
    </nav>

templates/posts/feed.html
{% extends "base.html" %}

{% block head_content %}
    <title>Platzigram</title>
{% endblock%}

{% block container %}
    <div class="container">
        <div class="row">

            {% for post in posts %}
            <div class="col-sm-12 col-md-8 offset-md-2 mt-5 p-0 post-container">
                <div class="media pt-3 pl-3 pb-1">
                    <a href="{% url 'users:detail' post.user.username %}">
                        <img class="mr-3 rounded-circle" height="35" src="{{ post.profile.picture.url }}" alt="{{ post.user.get_full_name }}">
                    </a>
                    <div class="media-body">
                        <p style="margin-top: 5px;">{{ post.user.get_full_name  }}</p>
                    </div>
                </div>

                <img style="width: 100%;" src="{{ post.photo.url }}" alt="{{ post.title }}">

                <p class="mt-1 ml-2" >
                    <a href="" style="color: #000; font-size: 20px;">
                        <i class="far fa-heart"></i>
                    </a> 30 likes
                </p>
                <p class="ml-2 mt-0 mb-2">
                    <b>{{ post.title }}</b> - <small>{{ post.created }}</small>
                </p>
            </div>
            {% endfor %}
        </div>
    </div>
    {% iclude 'pagination.html' %}

{% endblock %}

templates/posts/new.html
{% extends "base.html" %}

{% block head_content %}
<title>Create new post</title>
{% endblock %}

{% block container %}

    <div class="container">
        <div class="row justify-content-md-center">
            <div class="col-6 pt-3 pb-3" id="profile-box">
                <h4 class="mb-4">Post a new photo!</h4>

                <form method="POST" enctype="multipart/form-data">
                    {% csrf_token %}

                    <input type="hidden" name="user" value="{{ user.pk}}" />
                    <input type="hidden" name="profile" value="{{ profile.pk }}" />

                    {# Website field #}
                    <div class="form-group">
                        <input
                            class="form-control {% if form.title.errors %}is-invalid{% endif %}"
                            type="text"
                            name="title"
                            placeholder="Title"
                        >
                        <div class="invalid-feedback">
                            {% for error in form.title.errors %}{{ error }}{% endfor %}
                        </div>
                    </div>

                    {# Photo field #}
                    <div class="form-group">
                        <label>Choose your photo:</label>
                        <input
                            class="form-control {% if form.photo.errors %}is-invalid{% endif %}"
                            type="file"
                            name="photo"
                            placeholder="photo"
                        >
                        <div class="invalid-feedback">
                            {% for error in form.photo.errors %}{{ error }}{% endfor %}
                        </div>
                    </div>

                    <button type="submit" class="btn btn-primary btn-block mt-5">Publish!</button>
                </form>
            </div>
        </div>
    </div>

{% endblock %}

templates/users/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block head_content %}{% endblock %}

    {% load static %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" crossorigin="anonymous" />
    <link rel="stylesheet" href="{% static 'css/main.css' %}" />

</head>
<body class="h-100">

    <div class="container h-100">
        <div class="row h-100 justify-content-center align-items-center">
            <div class="col-sm-12 col-md-5 col-lg-5 pt-2 pl-5 pr-5 pb-5" id="auth-container">

                <img src="{% static "img/instagram.png" %}" class="img-fluid rounded mx-auto d-block pb-4" style="max-width: 60%;">

                {% block container %}{% endblock%}

            </div>
        </div>
    </div>

</body>
</html>

templates/users/detail.html
se.html" %}

{% block head_content %}
<title>@{{ user.username }} | Platzigram</title>
{% endblock %}

{% block container %}

<div class="container mb-5" style="margin-top: 8em;">
    <div class="row">

        <div class="col-sm-4 d-flex justify-content-center">
            <img src="{{ user.profile.picture.url }}" alt="@{{ user.username}}" class="rounded-circle" width="150px" />
        </div>

        <div class="col-sm-8">
            <h2 style="font-weight: 100;">
                {{ user.username }}
                {% if user == request.user %}
                <a href="{% url "users:update" %}" class="ml-5 btn btn-sm btn-outline-info">
                    Edit profile
                </a>
                {% else %}
                <a href="" class="ml-5 btn btn-sm btn-primary">
                    Follow
                </a>
                {% endif %}
            </h2>

            <div class="row mt-2" style="font-size: 1.2em">
                <div class="col-sm-4">
                    <b>{{ user.profile.posts_count }}785</b> posts
                </div>
                <div class="col-sm-4">
                    <b>{{ user.profile.followers }}1,401</b> followers
                </div>
                <div class="col-sm-4">
                    <b>{{ user.profile.following }}491</b> following
                </div>
            </div>
            <div class="row mt-4">
                <div class="col-sm-12">
                    <p>{{ user.profile.biography }}</p>
                </div>
            </div>
        </div>
    </div>
</div>

<hr>

<div class="container" id="user-posts">
    <div class="row mt-3">
        {% for post in posts %}
        <div class="col-sm-4 pt-5 pb-5 pr-5 pl-5 d-flex justify-content-center align-items-center">
            <a href="" class="border">
                <img src="{{ post.photo.url }}" alt="{{ post.title }}" class="img-fluid" />
            </a>
        </div>
        {% endfor %}
    </div>
</div>

{% endblock %}

templates/users/login.html
az{% extends "users/base.html" %}
{% block head_content %}
    <title> platzigram sing in</title>

{% endblock %}
{% block container %}

    {% if from.errors %}
    <p class="alert alert-danger">
    your user name and password didn't mactch 
    </p>
    {% endif %}
    <form method="POST" action="{% url "users:login" %}">
        {% csrf_token %}

        <div class = "form-group">
            <input class =  "from-control" type = "text" placeholder= "username" name="username">
        </div>

        <div class = "form-group">
            <input class =  "from-control" type="password" placeholder="*******" name="password" >
        </div>
        

        <button class = "btn btn-primary btn-block mt5" type="submit"> Sign In</button>
    </form>

    <p class="mt-4">Don't have an account yet? <a href = "{% url "users:signup" %}">Sign up here.</a></p>
{% endblock  %}

templates/users/signup.html
{% extends "users/base.html" %}

{% block head_content %}
<title>Platzigram sign up</title>
{% endblock %}

{% block container %}

    <form action="{% url 'signup' %}" method="POST">
        {% csrf_token %}
        
        {{ forms.as_p }}

        <button class="btn btn-primary btn-block mt-5" type="submit">Register!</button>

    </form>

{% endblock %}

templates/users/update.html
{% extends "base.html" %}
{% load static %}

{% block head_content %}
<title>@{{ request.user.username }} | Update profile</title>
{% endblock %}

{% block container %}

<div class="container">

    <div class="row justify-content-md-center">
        <div class="col-6 p-4" id="profile-box">

            <form action="{% url 'users:update' %}" method="POST" enctype="multipart/form-data">
                {% csrf_token %}

               
                <div class="media">
                    {% if profile.picture %}
                        <img src="{{ profile.picture.url }}" class="rounded-circle" height="50" />
                    {% else%}
                        <img src="{% static 'img/default-profile.png' %}" class="rounded-circle" height="50" />
                    {% endif %}

                    <div class="media-body">
                        <h5 class="ml-4">@{{ user.username }} | {{ user.get_full_name }}</h5>
                        <p class="ml-4"><input type="file" name="picture" required="true"></p>
                    </div>
                </div>
                {% for error in form.picture.errors %}
                    <div class = "alert alert-danger"> 
                    {{ error }}
                    </div>
                {% endfor %}

                <hr><br>

                <div class="form-group">
                    <label>Website</label>
                    <input
                        class="form-control {% if  form.website.errors  %} is-invalid {% endif %}"
                        type="url" 
                        name="website"
                        placeholder="Website"
                        value=" {% if  form.errors  %} {{ form.website.value}}  {% else %}  {{ profile.website }} {% endif %} "
                    />
                    <div class = "invalid-feedback" >
                        {% for error in form.website.errors %}
                            {{ error }}
                        {% endfor %}

                    </div>
                </div>

                <div class="form-group">
                    <label>Biography</label>
                    <textarea
                        class="form-control {% if  form.biography.errors  %} is-invalid {% endif %}"
                        name="biography"
                    >
                        value=" {% if  form.errors  %} {{ form.biography.value}}  {% else %}  {{ profile.biography }} {% endif %} 
                        
                    </textarea>
                    <div class = "invalid-feedback" >
                        {% for error in form.biographsy.errors %}
                            {{ error }}
                        {% endfor %}

                    </div>
                </div>

                <div class="form-group">
                    <label>Phone number</label>
                    <input
                        class="form-control {% if  form.phone_number.errors  %} is-invalid {% endif %}"
                        type="text"
                        name="phone_number"
                        placeholder="Phone number"
                        value="{{ profile.phone_number }}"
                    />
                    <div class = "invalid-feedback" >
                        {% for error in form.phone_numer.errors %}
                            {{ error }}
                        {% endfor %}

                    </div>
                </div>

                <button type="submit" class="btn btn-primary btn-block mt-5">Update info</button>
            </form>
        </div>
    </div>
</div>

{% endblock %}

templates/users/update_profile.html
{% extends "base.html" %}
{% load static %}

{% block head_content %}
<title>@{{ request.user.username }} | Update profile</title>
{% endblock %}

{% block container %}

<div class="container">

    <div class="row justify-content-md-center">
        <div class="col-6 p-4" id="profile-box">

            <form action="{% url 'update' %}" method="POST" enctype="multipart/form-data">
                {% csrf_token %}

               
                <div class="media">
                    {% if profile.picture %}
                        <img src="{{ profile.picture.url }}" class="rounded-circle" height="50" />
                    {% else%}
                        <img src="{% static 'img/default-profile.png' %}" class="rounded-circle" height="50" />
                    {% endif %}

                    <div class="media-body">
                        <h5 class="ml-4">@{{ user.username }} | {{ user.get_full_name }}</h5>
                        <p class="ml-4"><input type="file" name="picture" required="true"></p>
                    </div>
                </div>
                {% for error in form.picture.errors %}
                    <div class = "alert alert-danger"> 
                    {{ error }}
                    </div>
                {% endfor %}

                <hr><br>

                <div class="form-group">
                    <label>Website</label>
                    <input
                        class="form-control {% if  form.website.errors  %} is-invalid {% endif %}"
                        type="url" 
                        name="website"
                        placeholder="Website"
                        value=" {% if  form.errors  %} {{ form.website.value}}  {% else %}  {{ profile.website }} {% endif %} "
                    />
                    <div class = "invalid-feedback" >
                        {% for error in form.website.errors %}
                            {{ error }}
                        {% endfor %}

                    </div>
                </div>

                <div class="form-group">
                    <label>Biography</label>
                    <textarea
                        class="form-control {% if  form.biography.errors  %} is-invalid {% endif %}"
                        name="biography"
                    >
                        value=" {% if  form.errors  %} {{ form.biography.value}}  {% else %}  {{ profile.biography }} {% endif %} 
                        
                    </textarea>
                    <div class = "invalid-feedback" >
                        {% for error in form.biographsy.errors %}
                            {{ error }}
                        {% endfor %}

                    </div>
                </div>

                <div class="form-group">
                    <label>Phone number</label>
                    <input
                        class="form-control {% if  form.phone_number.errors  %} is-invalid {% endif %}"
                        type="text"
                        name="phone_number"
                        placeholder="Phone number"
                        value="{{ profile.phone_number }}"
                    />
                    <div class = "invalid-feedback" >
                        {% for error in form.phone_numer.errors %}
                            {{ error }}
                        {% endfor %}

                    </div>
                </div>

                <button type="submit" class="btn btn-primary btn-block mt-5">Update info</button>
            </form>
        </div>
    </div>
</div>

{% endblock %}